/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ECKeyStruct = {
  x: BigNumberish;
  y: BigNumberish;
  not_before: BigNumberish;
  not_after: BigNumberish;
};

export type ECKeyStructOutput = [
  x: bigint,
  y: bigint,
  not_before: bigint,
  not_after: bigint
] & { x: bigint; y: bigint; not_before: bigint; not_after: bigint };

export interface V1CertificateVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPCK"
      | "addPlatformCAKey"
      | "addRootKey"
      | "getPCK"
      | "owner"
      | "platformCertBodyHash"
      | "renounceOwnership"
      | "revokePCK"
      | "revokePlatformCA"
      | "rootCertBodyHash"
      | "transferOwnership"
      | "uintToBytesDER"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "addPCK",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addPlatformCAKey",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addRootKey",
    values: [ECKeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getPCK",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformCertBodyHash",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokePCK",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePlatformCA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rootCertBodyHash",
    values: [BytesLike, BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uintToBytesDER",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addPCK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addPlatformCAKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRootKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPCK", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformCertBodyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokePCK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokePlatformCA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rootCertBodyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uintToBytesDER",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface V1CertificateVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): V1CertificateVerifier;
  waitForDeployment(): Promise<this>;

  interface: V1CertificateVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPCK: TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      not_after: BytesLike,
      extensions: BytesLike,
      authority: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addPlatformCAKey: TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      extensions: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addRootKey: TypedContractMethod<[key: ECKeyStruct], [void], "nonpayable">;

  getPCK: TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [ECKeyStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformCertBodyHash: TypedContractMethod<
    [
      serial: BytesLike,
      not_before: BytesLike,
      not_after: BytesLike,
      x: BigNumberish,
      y: BigNumberish,
      extensions: BytesLike
    ],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokePCK: TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokePlatformCA: TypedContractMethod<
    [serial: BigNumberish],
    [void],
    "nonpayable"
  >;

  rootCertBodyHash: TypedContractMethod<
    [
      serial: BytesLike,
      not_before: BytesLike,
      x: BigNumberish,
      y: BigNumberish,
      extensions: BytesLike
    ],
    [string],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uintToBytesDER: TypedContractMethod<[n: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPCK"
  ): TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      not_after: BytesLike,
      extensions: BytesLike,
      authority: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addPlatformCAKey"
  ): TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      extensions: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRootKey"
  ): TypedContractMethod<[key: ECKeyStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getPCK"
  ): TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [ECKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformCertBodyHash"
  ): TypedContractMethod<
    [
      serial: BytesLike,
      not_before: BytesLike,
      not_after: BytesLike,
      x: BigNumberish,
      y: BigNumberish,
      extensions: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokePCK"
  ): TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokePlatformCA"
  ): TypedContractMethod<[serial: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rootCertBodyHash"
  ): TypedContractMethod<
    [
      serial: BytesLike,
      not_before: BytesLike,
      x: BigNumberish,
      y: BigNumberish,
      extensions: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uintToBytesDER"
  ): TypedContractMethod<[n: BigNumberish], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
