/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type RequestHeaderPatchStruct = { key: string; ciphertext: BytesLike };

export type RequestHeaderPatchStructOutput = [
  key: string,
  ciphertext: string
] & { key: string; ciphertext: string };

export type QueryParameterPatchStruct = { key: string; ciphertext: BytesLike };

export type QueryParameterPatchStructOutput = [
  key: string,
  ciphertext: string
] & { key: string; ciphertext: string };

export type HTTPPrivatePatchStruct = {
  pathSuffix: BytesLike;
  headers: RequestHeaderPatchStruct[];
  parameters: QueryParameterPatchStruct[];
  body: BytesLike;
};

export type HTTPPrivatePatchStructOutput = [
  pathSuffix: string,
  headers: RequestHeaderPatchStructOutput[],
  parameters: QueryParameterPatchStructOutput[],
  body: string
] & {
  pathSuffix: string;
  headers: RequestHeaderPatchStructOutput[];
  parameters: QueryParameterPatchStructOutput[];
  body: string;
};

export type RequestHeaderStruct = { key: string; value: string };

export type RequestHeaderStructOutput = [key: string, value: string] & {
  key: string;
  value: string;
};

export type QueryParameterStruct = { key: string; value: string };

export type QueryParameterStructOutput = [key: string, value: string] & {
  key: string;
  value: string;
};

export type HTTPRequestStruct = {
  method: BigNumberish;
  host: string;
  path: string;
  headers: RequestHeaderStruct[];
  parameters: QueryParameterStruct[];
  body: BytesLike;
};

export type HTTPRequestStructOutput = [
  method: bigint,
  host: string,
  path: string,
  headers: RequestHeaderStructOutput[],
  parameters: QueryParameterStructOutput[],
  body: string
] & {
  method: bigint;
  host: string;
  path: string;
  headers: RequestHeaderStructOutput[];
  parameters: QueryParameterStructOutput[];
  body: string;
};

export type FeedStruct = {
  request: HTTPRequestStruct;
  patch: HTTPPrivatePatchStruct;
  schema: string;
  filter: string;
};

export type FeedStructOutput = [
  request: HTTPRequestStructOutput,
  patch: HTTPPrivatePatchStructOutput,
  schema: string,
  filter: string
] & {
  request: HTTPRequestStructOutput;
  patch: HTTPPrivatePatchStructOutput;
  schema: string;
  filter: string;
};

export interface V1FeedRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addFeed"
      | "addJqFilter"
      | "addPrivatePatch"
      | "addRequest"
      | "addResponseSchema"
      | "changeFeedRegistryPolicy"
      | "changeTrustDomainRegistry"
      | "feeds"
      | "getFeed"
      | "jqFilters"
      | "owner"
      | "privatePatchTdIds"
      | "privatePatches"
      | "renounceOwnership"
      | "requests"
      | "resultSchemas"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeedAdded"
      | "JqFilterAdded"
      | "OwnershipTransferred"
      | "PrivatePatchAdded"
      | "RequestAdded"
      | "ResultSchemaAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addFeed",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "addJqFilter", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addPrivatePatch",
    values: [BigNumberish, HTTPPrivatePatchStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addRequest",
    values: [HTTPRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addResponseSchema",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "changeFeedRegistryPolicy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeTrustDomainRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "feeds", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getFeed", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "jqFilters",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "privatePatchTdIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "privatePatches",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "requests", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "resultSchemas",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addJqFilter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPrivatePatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addResponseSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeFeedRegistryPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeTrustDomainRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFeed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jqFilters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "privatePatchTdIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "privatePatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resultSchemas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FeedAddedEvent {
  export type InputTuple = [feedId: BytesLike];
  export type OutputTuple = [feedId: string];
  export interface OutputObject {
    feedId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JqFilterAddedEvent {
  export type InputTuple = [filterId: BytesLike];
  export type OutputTuple = [filterId: string];
  export interface OutputObject {
    filterId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivatePatchAddedEvent {
  export type InputTuple = [patchId: BytesLike];
  export type OutputTuple = [patchId: string];
  export interface OutputObject {
    patchId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestAddedEvent {
  export type InputTuple = [requestId: BytesLike];
  export type OutputTuple = [requestId: string];
  export interface OutputObject {
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultSchemaAddedEvent {
  export type InputTuple = [schemaId: BytesLike];
  export type OutputTuple = [schemaId: string];
  export interface OutputObject {
    schemaId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface V1FeedRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): V1FeedRegistry;
  waitForDeployment(): Promise<this>;

  interface: V1FeedRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addFeed: TypedContractMethod<
    [
      requestId: BytesLike,
      patchId: BytesLike,
      schemaId: BytesLike,
      filterId: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  addJqFilter: TypedContractMethod<[jqFilter: string], [string], "nonpayable">;

  addPrivatePatch: TypedContractMethod<
    [tdId: BigNumberish, privatePatch: HTTPPrivatePatchStruct],
    [string],
    "nonpayable"
  >;

  addRequest: TypedContractMethod<
    [request: HTTPRequestStruct],
    [string],
    "nonpayable"
  >;

  addResponseSchema: TypedContractMethod<
    [responseSchema: string],
    [string],
    "nonpayable"
  >;

  changeFeedRegistryPolicy: TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  changeTrustDomainRegistry: TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  feeds: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string] & {
        requestId: string;
        patchId: string;
        schemaId: string;
        filterId: string;
      }
    ],
    "view"
  >;

  getFeed: TypedContractMethod<
    [feedId: BytesLike],
    [[bigint, FeedStructOutput] & { tdId: bigint; feed: FeedStructOutput }],
    "view"
  >;

  jqFilters: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  privatePatchTdIds: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  privatePatches: TypedContractMethod<
    [arg0: BytesLike],
    [[string, string] & { pathSuffix: string; body: string }],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, string] & {
        method: bigint;
        host: string;
        path: string;
        body: string;
      }
    ],
    "view"
  >;

  resultSchemas: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addFeed"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      patchId: BytesLike,
      schemaId: BytesLike,
      filterId: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addJqFilter"
  ): TypedContractMethod<[jqFilter: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addPrivatePatch"
  ): TypedContractMethod<
    [tdId: BigNumberish, privatePatch: HTTPPrivatePatchStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRequest"
  ): TypedContractMethod<[request: HTTPRequestStruct], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addResponseSchema"
  ): TypedContractMethod<[responseSchema: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "changeFeedRegistryPolicy"
  ): TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeTrustDomainRegistry"
  ): TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeds"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string] & {
        requestId: string;
        patchId: string;
        schemaId: string;
        filterId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeed"
  ): TypedContractMethod<
    [feedId: BytesLike],
    [[bigint, FeedStructOutput] & { tdId: bigint; feed: FeedStructOutput }],
    "view"
  >;
  getFunction(
    nameOrSignature: "jqFilters"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "privatePatchTdIds"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "privatePatches"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[string, string] & { pathSuffix: string; body: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, string] & {
        method: bigint;
        host: string;
        path: string;
        body: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "resultSchemas"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeedAdded"
  ): TypedContractEvent<
    FeedAddedEvent.InputTuple,
    FeedAddedEvent.OutputTuple,
    FeedAddedEvent.OutputObject
  >;
  getEvent(
    key: "JqFilterAdded"
  ): TypedContractEvent<
    JqFilterAddedEvent.InputTuple,
    JqFilterAddedEvent.OutputTuple,
    JqFilterAddedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PrivatePatchAdded"
  ): TypedContractEvent<
    PrivatePatchAddedEvent.InputTuple,
    PrivatePatchAddedEvent.OutputTuple,
    PrivatePatchAddedEvent.OutputObject
  >;
  getEvent(
    key: "RequestAdded"
  ): TypedContractEvent<
    RequestAddedEvent.InputTuple,
    RequestAddedEvent.OutputTuple,
    RequestAddedEvent.OutputObject
  >;
  getEvent(
    key: "ResultSchemaAdded"
  ): TypedContractEvent<
    ResultSchemaAddedEvent.InputTuple,
    ResultSchemaAddedEvent.OutputTuple,
    ResultSchemaAddedEvent.OutputObject
  >;

  filters: {
    "FeedAdded(bytes32)": TypedContractEvent<
      FeedAddedEvent.InputTuple,
      FeedAddedEvent.OutputTuple,
      FeedAddedEvent.OutputObject
    >;
    FeedAdded: TypedContractEvent<
      FeedAddedEvent.InputTuple,
      FeedAddedEvent.OutputTuple,
      FeedAddedEvent.OutputObject
    >;

    "JqFilterAdded(bytes32)": TypedContractEvent<
      JqFilterAddedEvent.InputTuple,
      JqFilterAddedEvent.OutputTuple,
      JqFilterAddedEvent.OutputObject
    >;
    JqFilterAdded: TypedContractEvent<
      JqFilterAddedEvent.InputTuple,
      JqFilterAddedEvent.OutputTuple,
      JqFilterAddedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PrivatePatchAdded(bytes32)": TypedContractEvent<
      PrivatePatchAddedEvent.InputTuple,
      PrivatePatchAddedEvent.OutputTuple,
      PrivatePatchAddedEvent.OutputObject
    >;
    PrivatePatchAdded: TypedContractEvent<
      PrivatePatchAddedEvent.InputTuple,
      PrivatePatchAddedEvent.OutputTuple,
      PrivatePatchAddedEvent.OutputObject
    >;

    "RequestAdded(bytes32)": TypedContractEvent<
      RequestAddedEvent.InputTuple,
      RequestAddedEvent.OutputTuple,
      RequestAddedEvent.OutputObject
    >;
    RequestAdded: TypedContractEvent<
      RequestAddedEvent.InputTuple,
      RequestAddedEvent.OutputTuple,
      RequestAddedEvent.OutputObject
    >;

    "ResultSchemaAdded(bytes32)": TypedContractEvent<
      ResultSchemaAddedEvent.InputTuple,
      ResultSchemaAddedEvent.OutputTuple,
      ResultSchemaAddedEvent.OutputObject
    >;
    ResultSchemaAdded: TypedContractEvent<
      ResultSchemaAddedEvent.InputTuple,
      ResultSchemaAddedEvent.OutputTuple,
      ResultSchemaAddedEvent.OutputObject
    >;
  };
}
