/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type DataItemStruct = {
  timestamp: BigNumberish;
  feedId: BytesLike;
  value: BytesLike;
};

export type DataItemStructOutput = [
  timestamp: bigint,
  feedId: string,
  value: string
] & { timestamp: bigint; feedId: string; value: string };

export interface V1QuexRequestProcessorBaseInterface extends Interface {
  getFunction(nameOrSignature: "processResponse"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "processResponse",
    values: [BytesLike, DataItemStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "processResponse",
    data: BytesLike
  ): Result;
}

export interface V1QuexRequestProcessorBase extends BaseContract {
  connect(runner?: ContractRunner | null): V1QuexRequestProcessorBase;
  waitForDeployment(): Promise<this>;

  interface: V1QuexRequestProcessorBaseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  processResponse: TypedContractMethod<
    [requestId: BytesLike, response: DataItemStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "processResponse"
  ): TypedContractMethod<
    [requestId: BytesLike, response: DataItemStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
