/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type QEReportStruct = {
  CPUSVN: BytesLike;
  MISCSELECT: BytesLike;
  attributes: BytesLike;
  MRENCLAVE: BytesLike;
  MRSIGNER: BytesLike;
  ISVProdID: BytesLike;
  ISVSVN: BytesLike;
  REPORT_DATA1: BytesLike;
  REPORT_DATA2: BytesLike;
};

export type QEReportStructOutput = [
  CPUSVN: string,
  MISCSELECT: string,
  attributes: string,
  MRENCLAVE: string,
  MRSIGNER: string,
  ISVProdID: string,
  ISVSVN: string,
  REPORT_DATA1: string,
  REPORT_DATA2: string
] & {
  CPUSVN: string;
  MISCSELECT: string;
  attributes: string;
  MRENCLAVE: string;
  MRSIGNER: string;
  ISVProdID: string;
  ISVSVN: string;
  REPORT_DATA1: string;
  REPORT_DATA2: string;
};

export type TDQuoteStruct = {
  USER_DATA: BytesLike;
  TEE_TCB_SVN: BytesLike;
  MRSEAM: BytesLike;
  MRSIGNERSEAM: BytesLike;
  SEAMATTRIBUTES: BytesLike;
  TDATTRIBUTES: BytesLike;
  XFAM: BytesLike;
  MRTD: BytesLike;
  MRCONFIGD: BytesLike;
  MROWNER: BytesLike;
  MROWNERCONFIG: BytesLike;
  RTMR0: BytesLike;
  RTMR1: BytesLike;
  RTMR2: BytesLike;
  RTMR3: BytesLike;
  REPORT_DATA1: BytesLike;
  REPORT_DATA2: BytesLike;
};

export type TDQuoteStructOutput = [
  USER_DATA: string,
  TEE_TCB_SVN: string,
  MRSEAM: string,
  MRSIGNERSEAM: string,
  SEAMATTRIBUTES: string,
  TDATTRIBUTES: string,
  XFAM: string,
  MRTD: string,
  MRCONFIGD: string,
  MROWNER: string,
  MROWNERCONFIG: string,
  RTMR0: string,
  RTMR1: string,
  RTMR2: string,
  RTMR3: string,
  REPORT_DATA1: string,
  REPORT_DATA2: string
] & {
  USER_DATA: string;
  TEE_TCB_SVN: string;
  MRSEAM: string;
  MRSIGNERSEAM: string;
  SEAMATTRIBUTES: string;
  TDATTRIBUTES: string;
  XFAM: string;
  MRTD: string;
  MRCONFIGD: string;
  MROWNER: string;
  MROWNERCONFIG: string;
  RTMR0: string;
  RTMR1: string;
  RTMR2: string;
  RTMR3: string;
  REPORT_DATA1: string;
  REPORT_DATA2: string;
};

export interface V1QuoteVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addQE"
      | "addTD"
      | "getQE"
      | "getQEAuthority"
      | "getQEID"
      | "getTD"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addQE",
    values: [
      QEReportStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addTD",
    values: [
      TDQuoteStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "getQE", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getQEAuthority",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQEID",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getTD", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "addQE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addTD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getQE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getQEAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getQEID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTD", data: BytesLike): Result;
}

export interface V1QuoteVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): V1QuoteVerifier;
  waitForDeployment(): Promise<this>;

  interface: V1QuoteVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addQE: TypedContractMethod<
    [
      qe_report: QEReportStruct,
      platform_serial: BigNumberish,
      pck_serial: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  addTD: TypedContractMethod<
    [
      td_quote: TDQuoteStruct,
      qe_id: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      authentication_data: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getQE: TypedContractMethod<
    [qe_id: BigNumberish],
    [QEReportStructOutput],
    "view"
  >;

  getQEAuthority: TypedContractMethod<
    [qe_id: BigNumberish],
    [[bigint, bigint] & { platform_serial: bigint; pck_serial: bigint }],
    "view"
  >;

  getQEID: TypedContractMethod<[td_id: BigNumberish], [bigint], "view">;

  getTD: TypedContractMethod<
    [td_id: BigNumberish],
    [TDQuoteStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addQE"
  ): TypedContractMethod<
    [
      qe_report: QEReportStruct,
      platform_serial: BigNumberish,
      pck_serial: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTD"
  ): TypedContractMethod<
    [
      td_quote: TDQuoteStruct,
      qe_id: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      authentication_data: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getQE"
  ): TypedContractMethod<[qe_id: BigNumberish], [QEReportStructOutput], "view">;
  getFunction(
    nameOrSignature: "getQEAuthority"
  ): TypedContractMethod<
    [qe_id: BigNumberish],
    [[bigint, bigint] & { platform_serial: bigint; pck_serial: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQEID"
  ): TypedContractMethod<[td_id: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTD"
  ): TypedContractMethod<[td_id: BigNumberish], [TDQuoteStructOutput], "view">;

  filters: {};
}
