/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type DataItemStruct = {
  timestamp: BigNumberish;
  feedId: BytesLike;
  value: BytesLike;
};

export type DataItemStructOutput = [
  timestamp: bigint,
  feedId: string,
  value: string
] & { timestamp: bigint; feedId: string; value: string };

export type ETHSignatureStruct = {
  r: BytesLike;
  s: BytesLike;
  v: BigNumberish;
};

export type ETHSignatureStructOutput = [r: string, s: string, v: bigint] & {
  r: string;
  s: string;
  v: bigint;
};

export type RequestResultStruct = {
  tdId: BigNumberish;
  dataItem: DataItemStruct;
  signature: ETHSignatureStruct;
};

export type RequestResultStructOutput = [
  tdId: bigint,
  dataItem: DataItemStructOutput,
  signature: ETHSignatureStructOutput
] & {
  tdId: bigint;
  dataItem: DataItemStructOutput;
  signature: ETHSignatureStructOutput;
};

export interface V1RequestLogicInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAllowedAddress"
      | "calculateRequestPrice"
      | "changeFeedRegistry"
      | "changeTrustDomainRegistry"
      | "owner"
      | "processResponse"
      | "removeAllowedAddress"
      | "renounceOwnership"
      | "sendRequest"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "RequestCompleted"
      | "RequestCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAllowedAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateRequestPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "changeFeedRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeTrustDomainRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processResponse",
    values: [
      BytesLike,
      BytesLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      RequestResultStruct,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllowedAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAllowedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateRequestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeFeedRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeTrustDomainRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAllowedAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCompletedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    relayer: AddressLike,
    callbackAddress: AddressLike,
    callbackMethod: BytesLike,
    callbackGasLimit: BigNumberish,
    callbackSuccess: boolean
  ];
  export type OutputTuple = [
    requestId: string,
    relayer: string,
    callbackAddress: string,
    callbackMethod: string,
    callbackGasLimit: bigint,
    callbackSuccess: boolean
  ];
  export interface OutputObject {
    requestId: string;
    relayer: string;
    callbackAddress: string;
    callbackMethod: string;
    callbackGasLimit: bigint;
    callbackSuccess: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestCreatedEvent {
  export type InputTuple = [requestId: BytesLike, feedId: BytesLike];
  export type OutputTuple = [requestId: string, feedId: string];
  export interface OutputObject {
    requestId: string;
    feedId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface V1RequestLogic extends BaseContract {
  connect(runner?: ContractRunner | null): V1RequestLogic;
  waitForDeployment(): Promise<this>;

  interface: V1RequestLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAllowedAddress: TypedContractMethod<
    [address_: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateRequestPrice: TypedContractMethod<
    [callbackGasLimit: BigNumberish],
    [bigint],
    "view"
  >;

  changeFeedRegistry: TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  changeTrustDomainRegistry: TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processResponse: TypedContractMethod<
    [
      requestId: BytesLike,
      feedId: BytesLike,
      callbackAddress: AddressLike,
      callbackMethod: BytesLike,
      callbackGasLimit: BigNumberish,
      requestResult: RequestResultStruct,
      relayerAddress: AddressLike
    ],
    [void],
    "payable"
  >;

  removeAllowedAddress: TypedContractMethod<
    [address_: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendRequest: TypedContractMethod<[feedId: BytesLike], [string], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAllowedAddress"
  ): TypedContractMethod<[address_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "calculateRequestPrice"
  ): TypedContractMethod<[callbackGasLimit: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "changeFeedRegistry"
  ): TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeTrustDomainRegistry"
  ): TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processResponse"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      feedId: BytesLike,
      callbackAddress: AddressLike,
      callbackMethod: BytesLike,
      callbackGasLimit: BigNumberish,
      requestResult: RequestResultStruct,
      relayerAddress: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "removeAllowedAddress"
  ): TypedContractMethod<[address_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendRequest"
  ): TypedContractMethod<[feedId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequestCompleted"
  ): TypedContractEvent<
    RequestCompletedEvent.InputTuple,
    RequestCompletedEvent.OutputTuple,
    RequestCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RequestCreated"
  ): TypedContractEvent<
    RequestCreatedEvent.InputTuple,
    RequestCreatedEvent.OutputTuple,
    RequestCreatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequestCompleted(bytes32,address,address,bytes4,uint32,bool)": TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;
    RequestCompleted: TypedContractEvent<
      RequestCompletedEvent.InputTuple,
      RequestCompletedEvent.OutputTuple,
      RequestCompletedEvent.OutputObject
    >;

    "RequestCreated(bytes32,bytes32)": TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
    RequestCreated: TypedContractEvent<
      RequestCreatedEvent.InputTuple,
      RequestCreatedEvent.OutputTuple,
      RequestCreatedEvent.OutputObject
    >;
  };
}
