/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type QEReportStruct = {
  CPUSVN: BytesLike;
  MISCSELECT: BytesLike;
  attributes: BytesLike;
  MRENCLAVE: BytesLike;
  MRSIGNER: BytesLike;
  ISVProdID: BytesLike;
  ISVSVN: BytesLike;
  REPORT_DATA1: BytesLike;
  REPORT_DATA2: BytesLike;
};

export type QEReportStructOutput = [
  CPUSVN: string,
  MISCSELECT: string,
  attributes: string,
  MRENCLAVE: string,
  MRSIGNER: string,
  ISVProdID: string,
  ISVSVN: string,
  REPORT_DATA1: string,
  REPORT_DATA2: string
] & {
  CPUSVN: string;
  MISCSELECT: string;
  attributes: string;
  MRENCLAVE: string;
  MRSIGNER: string;
  ISVProdID: string;
  ISVSVN: string;
  REPORT_DATA1: string;
  REPORT_DATA2: string;
};

export type TDQuoteStruct = {
  USER_DATA: BytesLike;
  TEE_TCB_SVN: BytesLike;
  MRSEAM: BytesLike;
  MRSIGNERSEAM: BytesLike;
  SEAMATTRIBUTES: BytesLike;
  TDATTRIBUTES: BytesLike;
  XFAM: BytesLike;
  MRTD: BytesLike;
  MRCONFIGID: BytesLike;
  MROWNER: BytesLike;
  MROWNERCONFIG: BytesLike;
  RTMR0: BytesLike;
  RTMR1: BytesLike;
  RTMR2: BytesLike;
  RTMR3: BytesLike;
  REPORT_DATA1: BytesLike;
  REPORT_DATA2: BytesLike;
};

export type TDQuoteStructOutput = [
  USER_DATA: string,
  TEE_TCB_SVN: string,
  MRSEAM: string,
  MRSIGNERSEAM: string,
  SEAMATTRIBUTES: string,
  TDATTRIBUTES: string,
  XFAM: string,
  MRTD: string,
  MRCONFIGID: string,
  MROWNER: string,
  MROWNERCONFIG: string,
  RTMR0: string,
  RTMR1: string,
  RTMR2: string,
  RTMR3: string,
  REPORT_DATA1: string,
  REPORT_DATA2: string
] & {
  USER_DATA: string;
  TEE_TCB_SVN: string;
  MRSEAM: string;
  MRSIGNERSEAM: string;
  SEAMATTRIBUTES: string;
  TDATTRIBUTES: string;
  XFAM: string;
  MRTD: string;
  MRCONFIGID: string;
  MROWNER: string;
  MROWNERCONFIG: string;
  RTMR0: string;
  RTMR1: string;
  RTMR2: string;
  RTMR3: string;
  REPORT_DATA1: string;
  REPORT_DATA2: string;
};

export interface V1TrustDomainRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addQE"
      | "addTD"
      | "changeQuoteVerifier"
      | "disableTD"
      | "enableTD"
      | "getSignerAddress"
      | "isAllowed"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "addQE",
    values: [
      QEReportStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addTD",
    values: [
      TDQuoteStruct,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeQuoteVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disableTD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "enableTD",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSignerAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addQE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addTD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeQuoteVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disableTD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enableTD", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSignerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface V1TrustDomainRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): V1TrustDomainRegistry;
  waitForDeployment(): Promise<this>;

  interface: V1TrustDomainRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addQE: TypedContractMethod<
    [
      qeReport: QEReportStruct,
      platformSerial: BigNumberish,
      pckSerial: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  addTD: TypedContractMethod<
    [
      tdQuote: TDQuoteStruct,
      qeId: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      authenticationData: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  changeQuoteVerifier: TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  disableTD: TypedContractMethod<[tdId: BigNumberish], [void], "nonpayable">;

  enableTD: TypedContractMethod<[tdId: BigNumberish], [void], "nonpayable">;

  getSignerAddress: TypedContractMethod<[tdId: BigNumberish], [string], "view">;

  isAllowed: TypedContractMethod<[tdId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addQE"
  ): TypedContractMethod<
    [
      qeReport: QEReportStruct,
      platformSerial: BigNumberish,
      pckSerial: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTD"
  ): TypedContractMethod<
    [
      tdQuote: TDQuoteStruct,
      qeId: BigNumberish,
      x: BigNumberish,
      y: BigNumberish,
      authenticationData: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeQuoteVerifier"
  ): TypedContractMethod<
    [newContractAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disableTD"
  ): TypedContractMethod<[tdId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enableTD"
  ): TypedContractMethod<[tdId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getSignerAddress"
  ): TypedContractMethod<[tdId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<[tdId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
