/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  TestQuexResponseProcessor,
  TestQuexResponseProcessorInterface,
} from "../../../contracts/test_contracts/TestQuexResponseProcessor";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "feedId",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "value",
            type: "bytes",
          },
        ],
        internalType: "struct DataItem",
        name: "response",
        type: "tuple",
      },
    ],
    name: "badSignatureProcessor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "feedId",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "value",
            type: "bytes",
          },
        ],
        internalType: "struct DataItem",
        name: "response",
        type: "tuple",
      },
    ],
    name: "errorProcessor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "feedId",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "value",
            type: "bytes",
          },
        ],
        internalType: "struct DataItem",
        name: "response",
        type: "tuple",
      },
    ],
    name: "goodProcessor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576101c4908161001c8239f35b600080fdfe6080604052600436101561001257600080fd5b6000803560e01c80634657c1571461006857806376773c491461005457639e97b4cb1461003e57600080fd5b346100515761004c3661015b565b505080f35b80fd5b5034610051576100633661015b565b505080fd5b50346100515760203660031901126100515760043567ffffffffffffffff811161009e5761009a9036906004016100a2565b5080f35b5080fd5b9190606083820312610140576040805167ffffffffffffffff9260608201848111838210176101455783528195803583526020908181013582850152848101359086821161014057019180601f840112156101405782359086821161014557855196601f8301601f19908116603f01168801908111888210176101455786528187528282850101116101405780826000940183880137850101520152565b600080fd5b634e487b7160e01b600052604160045260246000fd5b90604060031983011261014057600435916024359067ffffffffffffffff82116101405761018b916004016100a2565b9056fea26469706673582212202a172b9adae4335f598da62b94351de5dda7984f55d8b68198db49c4954e8f1464736f6c63430008160033";

type TestQuexResponseProcessorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestQuexResponseProcessorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestQuexResponseProcessor__factory extends ContractFactory {
  constructor(...args: TestQuexResponseProcessorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestQuexResponseProcessor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TestQuexResponseProcessor__factory {
    return super.connect(runner) as TestQuexResponseProcessor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestQuexResponseProcessorInterface {
    return new Interface(_abi) as TestQuexResponseProcessorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestQuexResponseProcessor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TestQuexResponseProcessor;
  }
}
