/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type DataItemStruct = {
  timestamp: BigNumberish;
  feedId: BytesLike;
  value: BytesLike;
};

export type DataItemStructOutput = [
  timestamp: bigint,
  feedId: string,
  value: string
] & { timestamp: bigint; feedId: string; value: string };

export interface TestQuexResponseProcessorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "badSignatureProcessor"
      | "errorProcessor"
      | "goodProcessor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "badSignatureProcessor",
    values: [DataItemStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "errorProcessor",
    values: [BytesLike, DataItemStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "goodProcessor",
    values: [BytesLike, DataItemStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "badSignatureProcessor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "errorProcessor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "goodProcessor",
    data: BytesLike
  ): Result;
}

export interface TestQuexResponseProcessor extends BaseContract {
  connect(runner?: ContractRunner | null): TestQuexResponseProcessor;
  waitForDeployment(): Promise<this>;

  interface: TestQuexResponseProcessorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  badSignatureProcessor: TypedContractMethod<
    [response: DataItemStruct],
    [void],
    "nonpayable"
  >;

  errorProcessor: TypedContractMethod<
    [requestId: BytesLike, response: DataItemStruct],
    [void],
    "nonpayable"
  >;

  goodProcessor: TypedContractMethod<
    [requestId: BytesLike, response: DataItemStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "badSignatureProcessor"
  ): TypedContractMethod<[response: DataItemStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "errorProcessor"
  ): TypedContractMethod<
    [requestId: BytesLike, response: DataItemStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "goodProcessor"
  ): TypedContractMethod<
    [requestId: BytesLike, response: DataItemStruct],
    [void],
    "nonpayable"
  >;

  filters: {};
}
