/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type ECKeyStruct = {
  x: BigNumberish;
  y: BigNumberish;
  not_before: BigNumberish;
  not_after: BigNumberish;
};

export type ECKeyStructOutput = [
  x: bigint,
  y: bigint,
  not_before: bigint,
  not_after: bigint
] & { x: bigint; y: bigint; not_before: bigint; not_after: bigint };

export interface IV1CertificateVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPCK"
      | "addPlatformCAKey"
      | "getPCK"
      | "revokePCK"
      | "revokePlatformCA"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addPCK",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addPlatformCAKey",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPCK",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePCK",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokePlatformCA",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addPCK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addPlatformCAKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPCK", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokePCK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokePlatformCA",
    data: BytesLike
  ): Result;
}

export interface IV1CertificateVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): IV1CertificateVerifier;
  waitForDeployment(): Promise<this>;

  interface: IV1CertificateVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPCK: TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      not_after: BytesLike,
      extensions: BytesLike,
      authority: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  addPlatformCAKey: TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      extensions: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getPCK: TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [ECKeyStructOutput],
    "view"
  >;

  revokePCK: TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [void],
    "nonpayable"
  >;

  revokePlatformCA: TypedContractMethod<
    [serial: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPCK"
  ): TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      not_after: BytesLike,
      extensions: BytesLike,
      authority: BigNumberish,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addPlatformCAKey"
  ): TypedContractMethod<
    [
      x: BigNumberish,
      y: BigNumberish,
      serial: BigNumberish,
      not_before: BytesLike,
      extensions: BytesLike,
      r: BigNumberish,
      s: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPCK"
  ): TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [ECKeyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokePCK"
  ): TypedContractMethod<
    [platform_serial: BigNumberish, pck_serial: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokePlatformCA"
  ): TypedContractMethod<[serial: BigNumberish], [void], "nonpayable">;

  filters: {};
}
