/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type RequestHeaderPatchStruct = { key: string; ciphertext: BytesLike };

export type RequestHeaderPatchStructOutput = [
  key: string,
  ciphertext: string
] & { key: string; ciphertext: string };

export type QueryParameterPatchStruct = { key: string; ciphertext: BytesLike };

export type QueryParameterPatchStructOutput = [
  key: string,
  ciphertext: string
] & { key: string; ciphertext: string };

export type HTTPPrivatePatchStruct = {
  pathSuffix: BytesLike;
  headers: RequestHeaderPatchStruct[];
  parameters: QueryParameterPatchStruct[];
  body: BytesLike;
};

export type HTTPPrivatePatchStructOutput = [
  pathSuffix: string,
  headers: RequestHeaderPatchStructOutput[],
  parameters: QueryParameterPatchStructOutput[],
  body: string
] & {
  pathSuffix: string;
  headers: RequestHeaderPatchStructOutput[];
  parameters: QueryParameterPatchStructOutput[];
  body: string;
};

export type RequestHeaderStruct = { key: string; value: string };

export type RequestHeaderStructOutput = [key: string, value: string] & {
  key: string;
  value: string;
};

export type QueryParameterStruct = { key: string; value: string };

export type QueryParameterStructOutput = [key: string, value: string] & {
  key: string;
  value: string;
};

export type HTTPRequestStruct = {
  method: BigNumberish;
  host: string;
  path: string;
  headers: RequestHeaderStruct[];
  parameters: QueryParameterStruct[];
  body: BytesLike;
};

export type HTTPRequestStructOutput = [
  method: bigint,
  host: string,
  path: string,
  headers: RequestHeaderStructOutput[],
  parameters: QueryParameterStructOutput[],
  body: string
] & {
  method: bigint;
  host: string;
  path: string;
  headers: RequestHeaderStructOutput[];
  parameters: QueryParameterStructOutput[];
  body: string;
};

export type FeedStruct = {
  request: HTTPRequestStruct;
  patch: HTTPPrivatePatchStruct;
  schema: string;
  filter: string;
};

export type FeedStructOutput = [
  request: HTTPRequestStructOutput,
  patch: HTTPPrivatePatchStructOutput,
  schema: string,
  filter: string
] & {
  request: HTTPRequestStructOutput;
  patch: HTTPPrivatePatchStructOutput;
  schema: string;
  filter: string;
};

export interface IV1FeedRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addFeed"
      | "addJqFilter"
      | "addPrivatePatch"
      | "addRequest"
      | "addResponseSchema"
      | "getFeed"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addFeed",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "addJqFilter", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addPrivatePatch",
    values: [BigNumberish, HTTPPrivatePatchStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addRequest",
    values: [HTTPRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addResponseSchema",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getFeed", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "addFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addJqFilter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPrivatePatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addResponseSchema",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeed", data: BytesLike): Result;
}

export interface IV1FeedRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IV1FeedRegistry;
  waitForDeployment(): Promise<this>;

  interface: IV1FeedRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addFeed: TypedContractMethod<
    [
      requestId: BytesLike,
      patchId: BytesLike,
      filterId: BytesLike,
      schemaId: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  addJqFilter: TypedContractMethod<[jqFilter: string], [string], "nonpayable">;

  addPrivatePatch: TypedContractMethod<
    [tdId: BigNumberish, privatePatch: HTTPPrivatePatchStruct],
    [string],
    "nonpayable"
  >;

  addRequest: TypedContractMethod<
    [request: HTTPRequestStruct],
    [string],
    "nonpayable"
  >;

  addResponseSchema: TypedContractMethod<
    [responseSchema: string],
    [string],
    "nonpayable"
  >;

  getFeed: TypedContractMethod<
    [feedId: BytesLike],
    [[bigint, FeedStructOutput] & { tdId: bigint; feed: FeedStructOutput }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addFeed"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      patchId: BytesLike,
      filterId: BytesLike,
      schemaId: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addJqFilter"
  ): TypedContractMethod<[jqFilter: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addPrivatePatch"
  ): TypedContractMethod<
    [tdId: BigNumberish, privatePatch: HTTPPrivatePatchStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addRequest"
  ): TypedContractMethod<[request: HTTPRequestStruct], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "addResponseSchema"
  ): TypedContractMethod<[responseSchema: string], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getFeed"
  ): TypedContractMethod<
    [feedId: BytesLike],
    [[bigint, FeedStructOutput] & { tdId: bigint; feed: FeedStructOutput }],
    "view"
  >;

  filters: {};
}
