/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type DataItemStruct = {
  timestamp: BigNumberish;
  feedId: BytesLike;
  value: BytesLike;
};

export type DataItemStructOutput = [
  timestamp: bigint,
  feedId: string,
  value: string
] & { timestamp: bigint; feedId: string; value: string };

export type ETHSignatureStruct = {
  r: BytesLike;
  s: BytesLike;
  v: BigNumberish;
};

export type ETHSignatureStructOutput = [r: string, s: string, v: bigint] & {
  r: string;
  s: string;
  v: bigint;
};

export type RequestResultStruct = {
  tdId: BigNumberish;
  dataItem: DataItemStruct;
  signature: ETHSignatureStruct;
};

export type RequestResultStructOutput = [
  tdId: bigint,
  dataItem: DataItemStructOutput,
  signature: ETHSignatureStructOutput
] & {
  tdId: bigint;
  dataItem: DataItemStructOutput;
  signature: ETHSignatureStructOutput;
};

export interface IV1RequestLogicInterface extends Interface {
  getFunction(
    nameOrSignature: "calculateRequestPrice" | "processResponse" | "sendRequest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateRequestPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processResponse",
    values: [
      BytesLike,
      BytesLike,
      AddressLike,
      BytesLike,
      BigNumberish,
      RequestResultStruct,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sendRequest",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRequestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendRequest",
    data: BytesLike
  ): Result;
}

export interface IV1RequestLogic extends BaseContract {
  connect(runner?: ContractRunner | null): IV1RequestLogic;
  waitForDeployment(): Promise<this>;

  interface: IV1RequestLogicInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateRequestPrice: TypedContractMethod<
    [callbackGasLimit: BigNumberish],
    [bigint],
    "view"
  >;

  processResponse: TypedContractMethod<
    [
      requestId: BytesLike,
      feedId: BytesLike,
      callbackAddress: AddressLike,
      callbackMethod: BytesLike,
      callbackGasLimit: BigNumberish,
      requestResult: RequestResultStruct,
      relayerAddress: AddressLike
    ],
    [void],
    "payable"
  >;

  sendRequest: TypedContractMethod<[feedId: BytesLike], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateRequestPrice"
  ): TypedContractMethod<[callbackGasLimit: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "processResponse"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      feedId: BytesLike,
      callbackAddress: AddressLike,
      callbackMethod: BytesLike,
      callbackGasLimit: BigNumberish,
      requestResult: RequestResultStruct,
      relayerAddress: AddressLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "sendRequest"
  ): TypedContractMethod<[feedId: BytesLike], [string], "nonpayable">;

  filters: {};
}
