/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV1CertificateVerifier,
  IV1CertificateVerifierInterface,
} from "../../interfaces/IV1CertificateVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "serial",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "not_before",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "not_after",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "extensions",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "authority",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "r",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "s",
        type: "uint256",
      },
    ],
    name: "addPCK",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "serial",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "not_before",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "extensions",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "r",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "s",
        type: "uint256",
      },
    ],
    name: "addPlatformCAKey",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "platform_serial",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pck_serial",
        type: "uint256",
      },
    ],
    name: "getPCK",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "x",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "y",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "not_before",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "not_after",
            type: "uint256",
          },
        ],
        internalType: "struct ECKey",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "platform_serial",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pck_serial",
        type: "uint256",
      },
    ],
    name: "revokePCK",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "serial",
        type: "uint256",
      },
    ],
    name: "revokePlatformCA",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IV1CertificateVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IV1CertificateVerifierInterface {
    return new Interface(_abi) as IV1CertificateVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IV1CertificateVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IV1CertificateVerifier;
  }
}
