/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV1FeedRegistryPolicy,
  IV1FeedRegistryPolicyInterface,
} from "../../interfaces/IV1FeedRegistryPolicy";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "address_",
        type: "address",
      },
    ],
    name: "isAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IV1FeedRegistryPolicy__factory {
  static readonly abi = _abi;
  static createInterface(): IV1FeedRegistryPolicyInterface {
    return new Interface(_abi) as IV1FeedRegistryPolicyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IV1FeedRegistryPolicy {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IV1FeedRegistryPolicy;
  }
}
