/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV1FeedRegistry,
  IV1FeedRegistryInterface,
} from "../../interfaces/IV1FeedRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "patchId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "filterId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "schemaId",
        type: "bytes32",
      },
    ],
    name: "addFeed",
    outputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "jqFilter",
        type: "string",
      },
    ],
    name: "addJqFilter",
    outputs: [
      {
        internalType: "bytes32",
        name: "filterId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tdId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "bytes",
            name: "pathSuffix",
            type: "bytes",
          },
          {
            components: [
              {
                internalType: "string",
                name: "key",
                type: "string",
              },
              {
                internalType: "bytes",
                name: "ciphertext",
                type: "bytes",
              },
            ],
            internalType: "struct RequestHeaderPatch[]",
            name: "headers",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "string",
                name: "key",
                type: "string",
              },
              {
                internalType: "bytes",
                name: "ciphertext",
                type: "bytes",
              },
            ],
            internalType: "struct QueryParameterPatch[]",
            name: "parameters",
            type: "tuple[]",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
        ],
        internalType: "struct HTTPPrivatePatch",
        name: "privatePatch",
        type: "tuple",
      },
    ],
    name: "addPrivatePatch",
    outputs: [
      {
        internalType: "bytes32",
        name: "patchId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "enum RequestMethod",
            name: "method",
            type: "uint8",
          },
          {
            internalType: "string",
            name: "host",
            type: "string",
          },
          {
            internalType: "string",
            name: "path",
            type: "string",
          },
          {
            components: [
              {
                internalType: "string",
                name: "key",
                type: "string",
              },
              {
                internalType: "string",
                name: "value",
                type: "string",
              },
            ],
            internalType: "struct RequestHeader[]",
            name: "headers",
            type: "tuple[]",
          },
          {
            components: [
              {
                internalType: "string",
                name: "key",
                type: "string",
              },
              {
                internalType: "string",
                name: "value",
                type: "string",
              },
            ],
            internalType: "struct QueryParameter[]",
            name: "parameters",
            type: "tuple[]",
          },
          {
            internalType: "bytes",
            name: "body",
            type: "bytes",
          },
        ],
        internalType: "struct HTTPRequest",
        name: "request",
        type: "tuple",
      },
    ],
    name: "addRequest",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "responseSchema",
        type: "string",
      },
    ],
    name: "addResponseSchema",
    outputs: [
      {
        internalType: "bytes32",
        name: "schemaId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
    ],
    name: "getFeed",
    outputs: [
      {
        internalType: "uint256",
        name: "tdId",
        type: "uint256",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "enum RequestMethod",
                name: "method",
                type: "uint8",
              },
              {
                internalType: "string",
                name: "host",
                type: "string",
              },
              {
                internalType: "string",
                name: "path",
                type: "string",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "key",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "value",
                    type: "string",
                  },
                ],
                internalType: "struct RequestHeader[]",
                name: "headers",
                type: "tuple[]",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "key",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "value",
                    type: "string",
                  },
                ],
                internalType: "struct QueryParameter[]",
                name: "parameters",
                type: "tuple[]",
              },
              {
                internalType: "bytes",
                name: "body",
                type: "bytes",
              },
            ],
            internalType: "struct HTTPRequest",
            name: "request",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "bytes",
                name: "pathSuffix",
                type: "bytes",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "key",
                    type: "string",
                  },
                  {
                    internalType: "bytes",
                    name: "ciphertext",
                    type: "bytes",
                  },
                ],
                internalType: "struct RequestHeaderPatch[]",
                name: "headers",
                type: "tuple[]",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "key",
                    type: "string",
                  },
                  {
                    internalType: "bytes",
                    name: "ciphertext",
                    type: "bytes",
                  },
                ],
                internalType: "struct QueryParameterPatch[]",
                name: "parameters",
                type: "tuple[]",
              },
              {
                internalType: "bytes",
                name: "body",
                type: "bytes",
              },
            ],
            internalType: "struct HTTPPrivatePatch",
            name: "patch",
            type: "tuple",
          },
          {
            internalType: "string",
            name: "schema",
            type: "string",
          },
          {
            internalType: "string",
            name: "filter",
            type: "string",
          },
        ],
        internalType: "struct Feed",
        name: "feed",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IV1FeedRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IV1FeedRegistryInterface {
    return new Interface(_abi) as IV1FeedRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IV1FeedRegistry {
    return new Contract(address, _abi, runner) as unknown as IV1FeedRegistry;
  }
}
