/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV1QuoteVerifier,
  IV1QuoteVerifierInterface,
} from "../../interfaces/IV1QuoteVerifier";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes16",
            name: "CPUSVN",
            type: "bytes16",
          },
          {
            internalType: "bytes4",
            name: "MISCSELECT",
            type: "bytes4",
          },
          {
            internalType: "bytes16",
            name: "attributes",
            type: "bytes16",
          },
          {
            internalType: "bytes",
            name: "MRENCLAVE",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "MRSIGNER",
            type: "bytes32",
          },
          {
            internalType: "bytes2",
            name: "ISVProdID",
            type: "bytes2",
          },
          {
            internalType: "bytes2",
            name: "ISVSVN",
            type: "bytes2",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA1",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA2",
            type: "bytes32",
          },
        ],
        internalType: "struct QEReport",
        name: "qe_report",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "platform_serial",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pck_serial",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "r",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "s",
        type: "uint256",
      },
    ],
    name: "addQE",
    outputs: [
      {
        internalType: "uint256",
        name: "qe_id",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes20",
            name: "USER_DATA",
            type: "bytes20",
          },
          {
            internalType: "bytes16",
            name: "TEE_TCB_SVN",
            type: "bytes16",
          },
          {
            internalType: "bytes",
            name: "MRSEAM",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MRSIGNERSEAM",
            type: "bytes",
          },
          {
            internalType: "bytes8",
            name: "SEAMATTRIBUTES",
            type: "bytes8",
          },
          {
            internalType: "bytes8",
            name: "TDATTRIBUTES",
            type: "bytes8",
          },
          {
            internalType: "bytes8",
            name: "XFAM",
            type: "bytes8",
          },
          {
            internalType: "bytes",
            name: "MRTD",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MRCONFIGID",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MROWNER",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MROWNERCONFIG",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR0",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR1",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR2",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR3",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA1",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA2",
            type: "bytes32",
          },
        ],
        internalType: "struct TDQuote",
        name: "td_quote",
        type: "tuple",
      },
      {
        internalType: "uint256",
        name: "qe_id",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "y",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "authentication_data",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "r",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "s",
        type: "uint256",
      },
    ],
    name: "addTD",
    outputs: [
      {
        internalType: "uint256",
        name: "td_id",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "qe_id",
        type: "uint256",
      },
    ],
    name: "getQE",
    outputs: [
      {
        components: [
          {
            internalType: "bytes16",
            name: "CPUSVN",
            type: "bytes16",
          },
          {
            internalType: "bytes4",
            name: "MISCSELECT",
            type: "bytes4",
          },
          {
            internalType: "bytes16",
            name: "attributes",
            type: "bytes16",
          },
          {
            internalType: "bytes",
            name: "MRENCLAVE",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "MRSIGNER",
            type: "bytes32",
          },
          {
            internalType: "bytes2",
            name: "ISVProdID",
            type: "bytes2",
          },
          {
            internalType: "bytes2",
            name: "ISVSVN",
            type: "bytes2",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA1",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA2",
            type: "bytes32",
          },
        ],
        internalType: "struct QEReport",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "qe_id",
        type: "uint256",
      },
    ],
    name: "getQEAuthority",
    outputs: [
      {
        internalType: "uint256",
        name: "platform_serial",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pck_serial",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "td_id",
        type: "uint256",
      },
    ],
    name: "getQEID",
    outputs: [
      {
        internalType: "uint256",
        name: "qe_id",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "td_id",
        type: "uint256",
      },
    ],
    name: "getTD",
    outputs: [
      {
        components: [
          {
            internalType: "bytes20",
            name: "USER_DATA",
            type: "bytes20",
          },
          {
            internalType: "bytes16",
            name: "TEE_TCB_SVN",
            type: "bytes16",
          },
          {
            internalType: "bytes",
            name: "MRSEAM",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MRSIGNERSEAM",
            type: "bytes",
          },
          {
            internalType: "bytes8",
            name: "SEAMATTRIBUTES",
            type: "bytes8",
          },
          {
            internalType: "bytes8",
            name: "TDATTRIBUTES",
            type: "bytes8",
          },
          {
            internalType: "bytes8",
            name: "XFAM",
            type: "bytes8",
          },
          {
            internalType: "bytes",
            name: "MRTD",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MRCONFIGID",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MROWNER",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "MROWNERCONFIG",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR0",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR1",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR2",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "RTMR3",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA1",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "REPORT_DATA2",
            type: "bytes32",
          },
        ],
        internalType: "struct TDQuote",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IV1QuoteVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IV1QuoteVerifierInterface {
    return new Interface(_abi) as IV1QuoteVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IV1QuoteVerifier {
    return new Contract(address, _abi, runner) as unknown as IV1QuoteVerifier;
  }
}
