/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV1RequestRegistry,
  IV1RequestRegistryInterface,
} from "../../interfaces/IV1RequestRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "tdId",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "timestamp",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "feedId",
                type: "bytes32",
              },
              {
                internalType: "bytes",
                name: "value",
                type: "bytes",
              },
            ],
            internalType: "struct DataItem",
            name: "dataItem",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "r",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "s",
                type: "bytes32",
              },
              {
                internalType: "uint8",
                name: "v",
                type: "uint8",
              },
            ],
            internalType: "struct ETHSignature",
            name: "signature",
            type: "tuple",
          },
        ],
        internalType: "struct RequestResult",
        name: "requestResult",
        type: "tuple",
      },
    ],
    name: "processResponse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "feedId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "callbackAddress",
        type: "address",
      },
      {
        internalType: "bytes4",
        name: "callbackMethod",
        type: "bytes4",
      },
      {
        internalType: "uint32",
        name: "callbackGasLimit",
        type: "uint32",
      },
    ],
    name: "sendRequest",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "requestPrice",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IV1RequestRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IV1RequestRegistryInterface {
    return new Interface(_abi) as IV1RequestRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IV1RequestRegistry {
    return new Contract(address, _abi, runner) as unknown as IV1RequestRegistry;
  }
}
