/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IV1TrustDomainRegistry,
  IV1TrustDomainRegistryInterface,
} from "../../interfaces/IV1TrustDomainRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tdId",
        type: "uint256",
      },
    ],
    name: "getSignerAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tdId",
        type: "uint256",
      },
    ],
    name: "isAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IV1TrustDomainRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IV1TrustDomainRegistryInterface {
    return new Interface(_abi) as IV1TrustDomainRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IV1TrustDomainRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IV1TrustDomainRegistry;
  }
}
