/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "P256Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.P256Verifier__factory>;
    getContractFactory(
      name: "TestQuexResponseProcessor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TestQuexResponseProcessor__factory>;
    getContractFactory(
      name: "V1CertificateVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1CertificateVerifier__factory>;
    getContractFactory(
      name: "V1FeedRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1FeedRegistry__factory>;
    getContractFactory(
      name: "V1FeedRegistryPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1FeedRegistryPolicy__factory>;
    getContractFactory(
      name: "V1QuexRequestProcessorBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1QuexRequestProcessorBase__factory>;
    getContractFactory(
      name: "V1QuoteVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1QuoteVerifier__factory>;
    getContractFactory(
      name: "V1RequestLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1RequestLogic__factory>;
    getContractFactory(
      name: "V1RequestRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1RequestRegistry__factory>;
    getContractFactory(
      name: "V1TrustDomainRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.V1TrustDomainRegistry__factory>;
    getContractFactory(
      name: "IV1CertificateVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV1CertificateVerifier__factory>;
    getContractFactory(
      name: "IV1FeedRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV1FeedRegistry__factory>;
    getContractFactory(
      name: "IV1FeedRegistryPolicy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV1FeedRegistryPolicy__factory>;
    getContractFactory(
      name: "IV1QuoteVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV1QuoteVerifier__factory>;
    getContractFactory(
      name: "IV1RequestLogic",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV1RequestLogic__factory>;
    getContractFactory(
      name: "IV1RequestRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV1RequestRegistry__factory>;
    getContractFactory(
      name: "IV1TrustDomainRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IV1TrustDomainRegistry__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "P256Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.P256Verifier>;
    getContractAt(
      name: "TestQuexResponseProcessor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TestQuexResponseProcessor>;
    getContractAt(
      name: "V1CertificateVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1CertificateVerifier>;
    getContractAt(
      name: "V1FeedRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1FeedRegistry>;
    getContractAt(
      name: "V1FeedRegistryPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1FeedRegistryPolicy>;
    getContractAt(
      name: "V1QuexRequestProcessorBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1QuexRequestProcessorBase>;
    getContractAt(
      name: "V1QuoteVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1QuoteVerifier>;
    getContractAt(
      name: "V1RequestLogic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1RequestLogic>;
    getContractAt(
      name: "V1RequestRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1RequestRegistry>;
    getContractAt(
      name: "V1TrustDomainRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.V1TrustDomainRegistry>;
    getContractAt(
      name: "IV1CertificateVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IV1CertificateVerifier>;
    getContractAt(
      name: "IV1FeedRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IV1FeedRegistry>;
    getContractAt(
      name: "IV1FeedRegistryPolicy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IV1FeedRegistryPolicy>;
    getContractAt(
      name: "IV1QuoteVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IV1QuoteVerifier>;
    getContractAt(
      name: "IV1RequestLogic",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IV1RequestLogic>;
    getContractAt(
      name: "IV1RequestRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IV1RequestRegistry>;
    getContractAt(
      name: "IV1TrustDomainRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IV1TrustDomainRegistry>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "P256Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P256Verifier>;
    deployContract(
      name: "TestQuexResponseProcessor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestQuexResponseProcessor>;
    deployContract(
      name: "V1CertificateVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1CertificateVerifier>;
    deployContract(
      name: "V1FeedRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1FeedRegistry>;
    deployContract(
      name: "V1FeedRegistryPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1FeedRegistryPolicy>;
    deployContract(
      name: "V1QuexRequestProcessorBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1QuexRequestProcessorBase>;
    deployContract(
      name: "V1QuoteVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1QuoteVerifier>;
    deployContract(
      name: "V1RequestLogic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1RequestLogic>;
    deployContract(
      name: "V1RequestRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1RequestRegistry>;
    deployContract(
      name: "V1TrustDomainRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1TrustDomainRegistry>;
    deployContract(
      name: "IV1CertificateVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1CertificateVerifier>;
    deployContract(
      name: "IV1FeedRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1FeedRegistry>;
    deployContract(
      name: "IV1FeedRegistryPolicy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1FeedRegistryPolicy>;
    deployContract(
      name: "IV1QuoteVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1QuoteVerifier>;
    deployContract(
      name: "IV1RequestLogic",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1RequestLogic>;
    deployContract(
      name: "IV1RequestRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1RequestRegistry>;
    deployContract(
      name: "IV1TrustDomainRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1TrustDomainRegistry>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "P256Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.P256Verifier>;
    deployContract(
      name: "TestQuexResponseProcessor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TestQuexResponseProcessor>;
    deployContract(
      name: "V1CertificateVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1CertificateVerifier>;
    deployContract(
      name: "V1FeedRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1FeedRegistry>;
    deployContract(
      name: "V1FeedRegistryPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1FeedRegistryPolicy>;
    deployContract(
      name: "V1QuexRequestProcessorBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1QuexRequestProcessorBase>;
    deployContract(
      name: "V1QuoteVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1QuoteVerifier>;
    deployContract(
      name: "V1RequestLogic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1RequestLogic>;
    deployContract(
      name: "V1RequestRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1RequestRegistry>;
    deployContract(
      name: "V1TrustDomainRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.V1TrustDomainRegistry>;
    deployContract(
      name: "IV1CertificateVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1CertificateVerifier>;
    deployContract(
      name: "IV1FeedRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1FeedRegistry>;
    deployContract(
      name: "IV1FeedRegistryPolicy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1FeedRegistryPolicy>;
    deployContract(
      name: "IV1QuoteVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1QuoteVerifier>;
    deployContract(
      name: "IV1RequestLogic",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1RequestLogic>;
    deployContract(
      name: "IV1RequestRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1RequestRegistry>;
    deployContract(
      name: "IV1TrustDomainRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IV1TrustDomainRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
