/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  V1QuexRequestProcessorBase,
  V1QuexRequestProcessorBaseInterface,
} from "../../contracts/V1QuexRequestProcessorBase";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "feedId",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "value",
            type: "bytes",
          },
        ],
        internalType: "struct DataItem",
        name: "response",
        type: "tuple",
      },
    ],
    name: "processResponse",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class V1QuexRequestProcessorBase__factory {
  static readonly abi = _abi;
  static createInterface(): V1QuexRequestProcessorBaseInterface {
    return new Interface(_abi) as V1QuexRequestProcessorBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): V1QuexRequestProcessorBase {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as V1QuexRequestProcessorBase;
  }
}
